### ISSUE TITLE
migrate is not recognized

### ISSUE THREAD

**Issue by andrehendrata** [byjg/migration-cli#8]
Hi, Im really new to this
I've tried to install composer require "byjg/migration":"4.2.*"

and tried to run command migrate, the result is migrate not recognized

![image](https://user-images.githubusercontent.com/5380515/106796677-44c3bd80-668e-11eb-8d39-1e8a4f2d3191.png)

maybe something missing?
the same issue with vendor command and others

**Comment by byjg** [comment]
The Migration Command Line interface is in a different composer package. 

To use the CLI you just need:

```
composer require "byjg/migration-cli":"4.1.*"
```

After install you can access directly by:

```
vendor/bin/migrate 
```

Note that the project `byjg/migration-cli` has a different versioning. Migration Cli in the version 4.1 and the migration libraries are in the version 4.2.

**Comment by andrehendrata** [comment]
tried with both 4.1 and 4.2 still has not recognized error
![image](https://user-images.githubusercontent.com/5380515/106838182-5fb62200-66ce-11eb-9a2e-7bc417e36c9d.png)

migrate command also not recognized here

**Comment by byjg** [comment]
I just realize that you are using Windows. On Windows you need to run `php vendor/bin/migrate`

**Comment by andrehendrata** [comment]
> I just realize that you are using Windows. On Windows you need to run `php vendor/bin/migrate`

ok thank you, it works now
